### ISSUE TITLE
Add Up / Down option for Station PIDs

### ISSUE THREAD

**Issue by kineticscreen** [TransportVic/TransportVic2#107]
I know it might not have an analogous version on the network, but it would be great if in addition to the current options of * for all or the individual platform number, there were also the option for Up or Down to be requested.

This is particularly useful for stations such as North Melbourne, Burnley etc that have more than 1 platform that heads into the city.
Then it would be possible to create an FSS-Escalator display just for any trains going into the city, etc

**Comment by eyeballcode** [comment]
I've added this in as per a776895 - use U/D as the platform for up and down trains respectively
