### ISSUE TITLE
Bus Bay Mapping Completion Project

### ISSUE THREAD

**Issue by eyeballcode** [TransportVic/TransportVic2#11]
This issue tracks the completion of bus bay mapping

- [x] Chadstone SC
- [x] Oakleigh
- [x] Huntingdale
- [x] Monash Uni Clayton
- [x] Cranbourne
- [x] Cowes Transit Centre
- [x] Dandenong
- [x] Frankston
- [x] Berwick
- [x] Sunsine
- [x] Wyndham Vale
- [x] Werribee
- [x] Hoppers Crossing
- [x] Williams Landing
- [x] Lilydale
- [x] Croydon
- [x] Ringwood (Notes: No bay 3, 7)
- [x] Belgrave
- [x] Mitcham (Note: Bay 4 is unmarked)
- [x] Footscray (Note: Bays are scattered across RS and Mall)
- [x] Laverton
- [x] Newport (Note: No Bay 1, 4. Bays unmarked, data from station signage)
- [x] Geelong (Note: Some bays appear to be missing)
- [x] Bendigo
- [x] Sunbury
- [x] Watergardens
- [x] St. Albans
- [x] Heidelberg
- [x] Diamond Creek
- [x] Eltham
- [x] Melbourne Airport (Note: Only PTV Bays are marked)
- [x] Broadmeadows
- [x] Swanston Street (Note: Only Peak Bay 2 is marked)
- [x] Chirnside Park SC
- [x] Boronia
- [x] Craigieburn (Note: Only 1 bay despite numerous services)
- [x] Tarneit
- [x] Southern Cross (Note: Bay applies to 684 only)
- [x] Southern Cross Skybus
- [x] Southern Cross Coach
- [x] Glen Waverley (Note: No Bay 7, physical bays have numbering messed up)
- [x] Knox City SC
- [x] Box Hill (Note: GTFS Numbers not clearly marked, numbers reconstructed from timetables)
- [x] Bayswter
- [x] Doncaster SC
- [x] Reservoir (Note: Data surveyed after new interchange opened, but differs from PTV publication)
- [x] Epping
- [x] South Morang
- [x] Hawkstowe
- [x] Mernda
- [x] Stud Park SC
- [ ] The Pines SC
- [ ] Mentone
- [x] Eastland (Note: No bus bays)
- [x] Blackburn (Note: No bus bays)
- [x] Fountain Gate SC
- [x] Yarraville (Note: No bus bays)
- [x] Melton
- [x] Airport West SC (Note: No bus bays)
- [ ] Altona Gate SC
- [ ] Werribee Plaza
- [x] Northland
- [x] Rosanna (Note: No bus bays)
- [x] Clifton Hill Interchange (Note: No bus bays)
- [ ] Cheltenham
- [ ] Carrum
- [ ] Southland
- [ ] Sandringham
- [ ] Hampton
- [x] Moorabbin (Note: No bus bays)
- [x] Mordialloc (Note: No bus bays)
- [x] Donnybrook
- [x] Pakenham (Note: No bus bays)
- [ ] Warragul
- [x] Mitchell Street Central Bendigo (Note: GTFS Stops cannot be merged via name overrides as 5 KFlat-Huntly passes the **same** stop in both directions, leading to a mess of timings.)
- [x] Caroline Springs
- [x] Bacchus Marsh
- [x] Bairnsdale

**Comment by melbournefan** [comment]
Is this pulling data off OSM? because I'm sure there'd be a way to update it from there somehow

**Comment by eyeballcode** [comment]
Nope, I'm manually traveling out to survey the stops. At least that was before the virus.
I've checked OSM - it only has bay numbers for a handful of stations
Classic PTV has bus bays, but I'll rather verify it myself than rely on them

**Comment by melbournefan** [comment]
I'm gonna have to redo Tarneit, there appears to have been some changes and some routes are left without a bay allocated, I might have a pic on my server with a list of bays tho its gonna be a bit hard matching them if I'm not there...

Also Glenroy will have to be added if any bays appears when construction finishes
