### ISSUE TITLE
Invalid PID Type causes file download

### ISSUE THREAD

**Issue by melbournefan** [TransportVic/TransportVic2#12]
Issue: If 'PID Type' on the mockups page is invalid, it causes the browser to initiate a download of a file named 'get'

Browser: `Google Chrome 84.0.4147.105`

**Comment by TransportVic** [comment]
Ok I know why this is happening, but should this error be handled?
I'm thinking of an Error 400 page, which would just be the Error 500 page with a different title?

**Comment by melbournefan** [comment]
Yo, the error should lead to a 404 of some sort, or even a red outline on the button with a little dialogue like the bootstrap buttons do..

**Comment by TransportVic** [comment]
Updated in 206574a: PID types are now in a dropdown box so you can't go wrong with that. But keeping the error page in case people try and get smart and break it anyway
