### ISSUE TITLE
Highlight COVID-19 Curfew Cancellations

### ISSUE THREAD

**Issue by TransportVic** [TransportVic/TransportVic2#17]
With the new Stage 4 COVID-19 curfew being introduced late-night services are being cancelled. Thought it would be neat to tell the user exactly which ones are cancelled due to COVID-19.
Already have this done in 627a641 but only problem is that in the next GTFS update these services might be completely removed from the feed.
Also it's slightly annoying to have to manually account for works to get the TD numbers.

**Comment by TransportSG** [comment]
Potential solution in 8ee9edd
This fetches the day's cancellations from 7pm onwards - but at 5am in the morning
Given no reasonable service would be cancelled so early it must be a COVID-19 cancellation.

Will see how this works with the next timetable update

**Comment by TransportVic** [comment]
Data is made available at https://vic.transportsg.me/covid-19/curfew, will last until ptv breaks something

**Comment by TransportVic** [comment]
Indeed PTV has wiped the timetables clean of the services, these pages have been removed in fd41b81
