### ISSUE TITLE
PTV API Missing Vehicle Descriptor

### ISSUE THREAD

**Issue by mattfleaydaly** [TransportVic/TransportVic2#99]
PTV API dropped Vehicle Position and Descriptor.
Frontend however still displays, possible fallback?

**Comment by melbournefan** [comment]
It's back online from what I can see, also got full coverage of HCMT sets!

**Comment by melbournefan** [comment]
abort, abort lol.... well turns out that the run timings page isn't parsing the consist type image doh' though this is only sometimes happening and isn't affecting consist numbers
